### ISSUE TITLE
add `colormap_name` in algorithm

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geo-cogserver#81]
https://titiler-dev.undpgeohub.org/algorithms/rca

add `outputs.colormap_name`, so client can use it as defailt

![image](https://github.com/UNDP-Data/geo-cogserver/assets/2639701/576a8009-418a-4ea4-b91b-46c8f09ab2c3)

**Comment by iferencik** [comment]
closed by https://github.com/UNDP-Data/geo-cogserver/pull/86
